<a href="https://colab.research.google.com/github/Pritija11/workshop-1/blob/main/workshop_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
a = np.empty((2,2))
print(a)

[[7.63088150e-316 0.00000000e+000]
 [3.31971956e-316 7.01076740e-316]]


2. Initialize an all one array with size 4X2.


In [ ]:
import numpy as np
a = np.ones((4,2))
print(a)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:

arr = np.array([[1,2,3], [4,5,6]])
x = np.full(arr.shape, 5)
print(x)

[[5 5 5]
 [5 5 5]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
x = np.zeros(arr.shape)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
x = np.ones(arr.shape)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
a = np.array(new_list)
print(a)

[1 2 3 4]


1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
a = np.arange(10, 49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:

arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

arr = np.random.rand(30)
mean = np.mean(arr)

print("Array:", arr)
print("Mean:", mean)

Array: [0.06307076 0.21349353 0.42272838 0.48435513 0.28424951 0.77363916
 0.99324683 0.82069403 0.89232461 0.1383181  0.95027777 0.9147781
 0.45713474 0.47321312 0.69305599 0.90479514 0.60413693 0.87099393
 0.04402202 0.54680851 0.68066458 0.32778807 0.89111526 0.58452045
 0.15334004 0.96123289 0.51600359 0.14501314 0.77455978 0.78709412]
Mean: 0.578888940903619


5.Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
arr = np.random.rand(10, 10)

min_val = np.min(arr)
max_val = np.max(arr)

print("maximum value:", max_val)
print("minimum value:", min_val)




maximum value: 0.9979270169827753
minimum value: 0.003300734085792456


6.Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

arr = np.zeros(10)
arr[4] = 1

print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = np.array([1,2,0,0,4,0])
reverse = arr[ ::-1]

print(reverse)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


8.Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

board = np.ones((4,4), dtype=int)

board[1::2, ::2] = 0
board[::2, 1::2] = 0

print(board)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

sum1 = np.add(x,y)
sum2 = np.add(v,w)

print(sum1)
print(sum2)






[[ 6  8]
 [10 13]]
[20 22]


2. Subtract the two array.

In [ ]:
sub1 = np.subtract(x,y)
sub2 = np.subtract(v,w)

print(sub1)
print(sub2)


[[-4 -4]
 [-4 -3]]
[-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
a = x * 2
b = y * 2
c = v * 2
d = w * 2

print(a)
print(b)
print(c)
print(d)


[[ 2  4]
 [ 6 10]]
[[10 12]
 [14 16]]
[18 20]
[22 24]


4. Find the square of each element of the array.

In [ ]:
sqr1 = np.power(x,2)
sqr2 = np.power(y,2)
sqr3 = np.power(v,2)
sqr4 = np.power(w,2)

print(sqr1)
print(sqr2)
print(sqr3)
print(sqr4)


[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


5.
Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dotProduct1 = np.dot(v,w)
dotProduct2 = np.dot(x,v)
dotProduct3 = np.dot(x,y)

print(dotProduct1)
print(dotProduct2)
print(dotProduct3)


219
[29 77]
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
concat_row = np.vstack((x,y))
v_col = v.reshape(2,1)
w_col = w.reshape(2,1)

concat_col = np.hstack((v_col, w_col))

print(concat_row)
print(concat_col)


[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


7.Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

numpy cannot concatenate arrays of different dimension

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

C = np.linalg.inv(A)
D = np.dot(A, C)
I = np.eye(2)

print(I)
print(D)


[[1. 0.]
 [0. 1.]]
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


3. Prove (AB)

T = BTAT
.

In [ ]:
AB = np.dot(A, B)
AB_T = np.transpose(AB)

B_T = np.transpose(B)
A_T = np.transpose(A)

B_T_A_T = np.dot(B_T, A_T)

print(AB_T)
print(B_T_A_T)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print(x)


[[1 2]
 [3 5]]


1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [1]:
import time
import numpy as np

size = 1000000

a = list(range(size))
b = list(range(size))

start = time.time()

c = [a[i] + b[i] for i in range(len(a))]

end = time.time()

d = end - start
print("python list time:", d)


arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

arr_sum = arr1 + arr2

end = time.time()
d = end - start

print("numpy array time:", d)

python list time: 0.22489309310913086
numpy array time: 0.005215644836425781


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [2]:
import time
import numpy as np

size = 1000000
a = list(range(size))
b = list(range(size))

start = time.time()
c = [a[i] * b[i] for i in range(len(a))]
end = time.time()
t = end - start
print("Python list time:", t)

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
arr_mul = arr1 * arr2
end = time.time()
t = end - start
print("NumPy array time:", t)


Python list time: 0.11669254302978516
NumPy array time: 0.003922224044799805


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [3]:
import time
import numpy as np

size = 1000000
a = list(range(size))
b = list(range(size))

start = time.time()
dot = sum(a[i] * b[i] for i in range(len(a)))
end = time.time()
t = end - start
print("Python list time:", t)

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
t = end - start
print("NumPy array time:", t)


Python list time: 0.11022305488586426
NumPy array time: 0.0016481876373291016


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [8]:
import time
import numpy as np
import random

size = 1000
A = [[random.random() for _ in range(size)] for _ in range(size)]
B = [[random.random() for _ in range(size)] for _ in range(size)]

start = time.time()

result = [[0 for _ in range(size)] for _ in range(size)]


for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()
t = end - start
print("Python list time:", t)

arr1 = np.random.rand(size, size)
arr2 = np.random.rand(size, size)

start = time.time()
result_np =  arr1 @ arr2
end = time.time()
t = end - start
print("NumPy array time:", t)




Python list time: 341.06574058532715
NumPy array time: 0.05562758445739746
